name: Publish on \# cheatsheet
on: 
  push:
    branches:
      - master
      - tmp
    paths:
      - 'text/**'

jobs:
  Publish-On-Cheatsheet:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      #- name: Install dependencies
      #  run: pip install any-package-you-need

      - name: Extract name from changed file
        id: extract_name
        run: |
          CHANGED_FILE=$(git diff --name-only HEAD -- 'text/*.txt' | head -n 1)
          CHEATSHEET=$(basename "$CHANGED_FILE" .txt)
          echo "cheathsheet=$CHEATSHEET" >> $GITHUB_OUTPUT

      - name: Create ANSI directory
        run: |
          mkdir -p "ansi/${{ steps.extract_chapter.outputs.cheathsheet }}"
          touch "ansi/${{ steps.extract_chapter.outputs.cheathsheet }}/.gitkeep"

      - name: Commit and push generated ANSI files
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add "ansi/${{ steps.extract_chapter.outputs.chapter_name }}"
          git commit -m "Auto-generated ANSI files for ${{ steps.extract_chapter.outputs.chapter_name }}"
          git push

      - name: Extract event data
        id: event-data
        uses: actions/github-script@v6
        with:
          script: |
            const eventData = {
              ref: context.ref,
              repository: context.repo
            }
            return JSON.stringify(eventData)
      - name: Post Cheatsheet on Discord
        uses: fjogeleit/http-request-action@v1
        with:
          url: 'http://localhost:8000/cheatsheet/action'
          method: 'POST'
          customHeaders: '{"Content-Type": "application/json", "X-API-Key": "secret"}'
          data: ${{ steps.event-data.outputs.result }}
          timeout: 15000
