name: Publish on \# cheatsheet
on: 
  push:
    branches:
      - master
      - tmp
    paths:
      - 'text/**'

jobs:
  Publish-On-Cheatsheet:
    runs-on: ubuntu-latest
    steps:
      - name: Extract event data
        id: event-data
        uses: actions/github-script@v6
        with:
          script: |
            const eventData = {
              ref: context.ref,
              repository: context.repo
            }
            return JSON.stringify(eventData)
      - name: Post Cheatsheet on Discord
        uses: fjogeleit/http-request-action@v1
        with:
          url: 'http://localhost:8000/cheatsheet/action'
          method: 'POST'
          customHeaders: '{"Content-Type": "application/json", "X-API-Key": "secret"}'
          data: ${{ steps.event-data.outputs.result }}
          timeout: 15000
