name: Publish on \# cheatsheet
on: 
  push:
    branches:
      - master
      - tmp
    paths:
      - 'text/**'
permissions: write-all
jobs:
  Publish-On-Cheatsheet:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Get all changed markdown files
        id: changed-markdown-files
        uses: tj-actions/changed-files@ed68ef82c095e0d48ec87eccea555d944a631a4c
        with:
          files: text/**.txt

      - name: Debug
        env: 
          CHANGED_FILE: ${{ steps.changed-markdown-files.outputs.all_modified_files }}
        run: echo "${{ env.CHANGED_FILE }}" 

      - name: Assert cheathsheet name is not empty
        if: ${{ env.CHANGED_FILE  == '' }}
        run: exit 1

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      #- name: Install dependencies
      #  run: pip install any-package-you-need


      - name: Create ANSI directory
        run: |
          mkdir -p "ansi/${{ env.CHANGED_FILE }}"
          touch "ansi/${{ env.CHANGED_FILE }}/.gitkeep"

      - name: Commit and push generated ANSI files
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add "ansi/${{ env.CHANGED_FILE }}"
          git commit -m "Auto-generated ANSI files for ${{ env.CHANGED_FILE }}"
          git push

      - name: Extract event data
        id: event-data
        uses: actions/github-script@v7
        with:
          script: |
            const eventData = {
              ref: context.ref,
              repository: context.repo
            }
            return JSON.stringify(eventData)

      - name: Post Cheatsheet on Discord
        uses: fjogeleit/http-request-action@v1
        with:
          url: 'http://localhost:8000/cheatsheet/action'
          method: 'POST'
          customHeaders: '{"Content-Type": "application/json", "X-API-Key": "secret"}'
          data: ${{ steps.event-data.outputs.result }}
          timeout: 15000
